name: Deploy to Server

on:
  push:
    branches:
      - master # 触发的分支

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}     # 服务器IP
          username: ${{ secrets.SERVER_USER }} # 服务器用户名
          key: ${{ secrets.SERVER_SSH_KEY }}   # 服务器私钥
          port: ${{ secrets.SERVER_PORT || 22 }}
          script: |
            mkdir -p ~/github
            cd ~/github
            if [ ! -d "lol-me-portal" ]; then
              git clone https://github.com/alongLFB/lol-me-portal.git
            fi
            cd lol-me-portal
            git pull origin master
            echo "${{ secrets.ENV_FILE }}" > .env.local
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            rm -rf .next
            npm ci
            npm run build
            export APP_PORT=$(grep -E '^PORT=' .env.local | cut -d '=' -f2)
            export APP_PORT=${APP_PORT:-3007}
            pm2 restart lol-me-portal --update-env || pm2 start npm --name "lol-me-portal" -- start -- -p $APP_PORT
